development:
  clients:
    default:
      database: dummy_app_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: dummy_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
